config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  authenticated :user do
    root 'applicants#show', as: :user_authenticated_root
  end
  devise_for :heads, controllers: {
    sessions: 'heads/sessions',
    registrations: 'heads/registrations'
  }
  authenticated :head do
    root 'head_profiles#index', as: :head_authenticated_root
  end
  root 'home#index'
  resources :applicants, only: %i[index show new create edit update] do
    resources :favorites, only: %i[create destroy]
    resources :posts, only: %i[show new create edit update destroy]
  end
  resources :feedbacks, only: [:index]
  resources :head_profiles, only: [:index]
  resources :job_offers, only: %i[index]
  resources :reply_offers, only: %i[index new create]
  resources :job_openings, only: [:index]
  resources :job_vacancies, only: %i[index show new create] do
    get 'search', on: :collection
    resources :feedbacks, only: %i[show new create]
    resources :job_offers, only: %i[new create]
    resources :job_openings, only: %i[show new create]
  end
end

app/models/job_vacancy.rb
# frozen_string_literal: true

class JobVacancy < ApplicationRecord
  belongs_to :head

  validates :title, :job_description, :desired_skills, :income_range,
            :job_level, :deadline, :area,
            presence: true, length: { maximum: 4000 }
  validate :valid_date

  scope :search, lambda { |query|
                   where('title LIKE ?', "%#{query}%")
                     .or(where('job_description LIKE ?', "%#{query}%"))
                 }

  def valid_date
    errors.add(:deadline, 'não pode ser anterior a hoje') if deadline.present? && deadline < Date.today
  end
end

app/controllers/job_vacancies_controller.rb
# frozen_string_literal: true

class JobVacanciesController < ApplicationController
  before_action :authenticate_head!, only: %i[new create]
  before_action :authenticate_user!, only: %i[index]
  before_action :authenticate_visitor, only: %i[index search]

  def index
    @job_vacancies = JobVacancy.all
  end

  def show
    @job_vacancy = JobVacancy.find(params[:id])
    @job_openings = JobOpening.where(job_vacancy: @job_vacancy)
    if user_signed_in?
      @applicant = Applicant.find_by(user: current_user)
      @job_openings = JobOpening.where(applicant: @applicant, job_vacancy: @job_vacancy)
    end
  end

  def new
    @job_vacancy = JobVacancy.new
  end

  def create
    @job_vacancy = JobVacancy.create(job_params)
    @job_vacancy.head = current_head
    if @job_vacancy.save
      flash[:notice] = 'Vaga cadastrada com sucesso'
      redirect_to @job_vacancy
    else
      render :new
    end
  end

  def search
    @job_vacancies = JobVacancy.search(params[:q])
    render :index
  end

  private

  def job_params
    params.require(:job_vacancy).permit(:title, :job_description,
                                        :desired_skills,
                                        :income_range, :job_level, :deadline,
                                        :area, :head_id)
  end

  def authenticate_visitor
    redirect_to root_path unless user_signed_in? || head_signed_in?
    if user_signed_in?
      @applicant = Applicant.find_by(user: current_user)
      redirect_to new_applicant_path if @applicant.blank?
    end
  end
end

app/views/job_vacancies/_entree.erb
<h3>Candidatos:</h3>

<% if @job_openings.present? %>
		<% @job_openings.each do |j| %>
			<p><strong>Nome: </strong> <%= link_to j.applicant.full_name,
																							 applicant_path(j.applicant) %>
			<p><strong>Formação: </strong> <%= j.applicant.academic %></p>
			<dt><strong>Carta:</strong></dt>
			<dd><%= j.letter %></dd>
			<p><strong>Status do Processo: </strong> 
			<%= JobOpening.human_attribute_name("status.#{j.status}") %></p>
			<p><%= link_to 'Recusar e enviar Feedback', 
									new_job_vacancy_feedback_path(@job_vacancy) %></p>	
			<p><%= link_to 'Aceitar e enviar Proposta', 
									new_job_vacancy_job_offer_path(@job_vacancy) %></p>	
		<%end%>
	<%else%>
	<p>Nenhuma candidatura foi realizada</p>
<% end %>

app/views/job_vacancies/_form.erb
<%@job_vacancy.errors.full_messages.each do |message|%>
  <b><%= message %><b></br>
<%end%>

<%= form_for @job_vacancy do |f| %>
  <%= f.label :title, "Vaga"%>
  <%= f.text_field :title%><br>
  <%= f.label :job_description, "Descrição da vaga"%>
  <%= f.text_field :job_description%><br>
  <%= f.label :desired_skills, "Habilidades desejáveis"%>
  <%= f.text_field :desired_skills%><br>
  <%= f.label :income_range, "Faixa salarial"%>
  <%= f.select :income_range, ['R$1000,00 a R$2000,00', 'R$2000,00 a R$3000,00',
                               'R$4000,00 a R$5000,00', 'maior que R$5000,00', 
                               'a combinar']%><br>
  <%= f.label :job_level, 'Nível da vaga'%><br>
  <%= f.select :job_level, ['estágio', 'júnior', 'pleno','sênior',
                            'especialista','diretor']%>
  <%= f.label :deadline, "Data limite"%>
  <%= f.date_field :deadline%><br>
  <%= f.label :area, 'Localização da vaga'%>
  <%= f.text_field :area%>
  <%= f.submit "Enviar"%>
<%end%>
  

app/views/job_vacancies/index.html.erb
<h1>Vagas de emprego</h1>

<%= render 'shared/search' %>
<br><br>
<%= render 'shared/jobs' %>
<br>
<p><%= link_to "Voltar", root_path %></p>

app/views/job_vacancies/new.html.erb
<h1>Cadastar Vaga de emprego</h1>

<%= render 'form' %>

app/views/job_vacancies/show.html.erb
<h1>Dados da Vaga de emprego</h1>

<dl>
<dt>Vaga: </dt>
<dd><%= @job_vacancy.title%></dd>
<dt>Descrição da Vaga: </dt>
<dd><%= @job_vacancy.job_description%></dd>
<dt>Habilidades desejáveis</dt>
<dd><%= @job_vacancy.desired_skills%></dd>
<dt>Faixa salarial: </dt>
<dd><%= @job_vacancy.income_range%></dd>
<dt>Nível da vaga: </dt>
<dd><%= @job_vacancy.job_level%></dd>
<dt>Data limite:</dt>
<dd><%= l(@job_vacancy.deadline)%></dd>
<dt>Localização da vaga:</dt>
<dd><%= @job_vacancy.area%></dd>
<% if head_signed_in? %>
	<%= render "entree" %>
<%end%>
<% if user_signed_in? %> 
  <% if @job_openings.any? %>
  <p><%= link_to 'Ver minha candidatura', job_vacancy_job_opening_path(@job_vacancy,
                       @job_vacancy) %></p>
  <%else%>
  <p><%= link_to 'Me candidatar', new_job_vacancy_job_opening_path(@job_vacancy) %></p>
  <%end%>
<%end%>
<%= link_to "Voltar", root_path %>