config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  authenticated :user do
    root 'applicants#show', as: :user_authenticated_root
  end
  devise_for :heads, controllers: {
    sessions: 'heads/sessions',
    registrations: 'heads/registrations'
  }
  authenticated :head do
    root 'head_profiles#index', as: :head_authenticated_root
  end
  root 'home#index'
  resources :applicants, only: %i[index show new create edit update] do
    resources :favorites, only: %i[create destroy]
    resources :posts, only: %i[show new create edit update destroy]
  end
  resources :feedbacks, only: [:index]
  resources :head_profiles, only: [:index]
  resources :job_offers, only: %i[index]
  resources :reply_offers, only: %i[index new create]
  resources :job_openings, only: [:index]
  resources :job_vacancies, only: %i[index show new create] do
    get 'search', on: :collection
    resources :feedbacks, only: %i[show new create]
    resources :job_offers, only: %i[new create]
    resources :job_openings, only: %i[show new create]
  end
end

app/models/applicant.rb
# frozen_string_literal: true

class Applicant < ApplicationRecord
  has_one_attached :photo
  belongs_to :user

  validates :full_name, :social_name, :birthdate, :academic, :description,
            :experience, presence: true
  validates :description, length: { maximum: 1000 }
  validate :older_than_sixteen

  def older_than_sixteen
    errors.add(:birthdate, 'não pode ser menos que 16 anos') if birthdate.present? && birthdate > 16.years.ago
  end
end

app/controllers/applicants_controller.rb
# frozen_string_literal: true

class ApplicantsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :authenticate_head!, only: %i[index]
  before_action :authenticate_visitor, only: %i[show]
  before_action :profile_owner, only: %i[edit update]

  def index
    @applicants = Applicant.all
  end

  def show
    if user_signed_in?
      if @applicant = Applicant.find_by(user: current_user)
        @posts = Post.where(applicant: @applicant)
      else
        redirect_to new_applicant_path
      end
    end
    if head_signed_in?
      @applicant = Applicant.find_by(params[:id])
      @posts = Post.where(head: current_head, applicant: @applicant)
      @favorite = Favorite.where(head_id: current_head, applicant_id: @applicant)
    end
  end

  def new
    @applicant = Applicant.new
  end

  def create
    @applicant = Applicant.create(applicant_params)
    @applicant.user = current_user
    if @applicant.save
      flash[:notice] = 'Perfil criado com sucesso'
      redirect_to root_path
    end
  end

  def edit
    @applicant = Applicant.find(params[:id])
  end

  def update
    @applicant = Applicant.find(params[:id])
    if @applicant.update(applicant_params)
      redirect_to @applicant
    else
      render :edit
    end
  end

  private

  def applicant_params
    params.require(:applicant).permit(:full_name, :social_name, :birthdate,
                                      :academic, :description, :experience,
                                      :photo, :user_id)
  end

  def profile_owner
    @applicant = Applicant.find(params[:id])
    if @applicant.user != current_user
      redirect_to root_path
      flash[:alert] = 'Ação não permitida'
    end
  end

  def authenticate_visitor
    redirect_to root_path unless user_signed_in? || head_signed_in?
  end
end

app/views/applicants/_form.erb
<%@applicant.errors.full_messages.each do |message|%>
  <b><%= message %><b></br>
<%end%>

<%= form_for @applicant do |f| %>
  <%= f.label :full_name, "Nome completo"%>
  <%= f.text_field :full_name%><br>
  <%= f.label :social_name, "Nome social"%>
  <%= f.text_field :social_name%><br>
  <%= f.label :birthdate, "Data de nascimento"%>
  <%= f.date_field :birthdate%><br>
  <%= f.label :academic, "Formação"%>
  <%= f.text_field :academic%><br>
  <%= f.label :description, "Descrição"%>
  <%= f.text_field :description %><br>
  <%= f.label :experience, "Experiência Profissional"%>
  <%= f.text_field :experience%><br>
  <%= f.label :photo, "Foto"%>
  <%= f.file_field :photo%><br>

  <%= f.submit "Enviar"%>
<%end%>
  

app/views/applicants/edit.html.erb
<h1>Editar Perfil</h1>

<%= render 'form' %>

app/views/applicants/index.html.erb
<h1>Candidatos cadastrados</h1>
<% if @applicants.empty? %>
	<p><%= 'Nenhuma candidatura registrada' %></p>
<%else%>
	<% @applicants.each do |applicant| %>
	<% if applicant.photo.present? %>
		<%= image_tag applicant.photo, size: "210x150", alt: 'Foto' %> 
		<%else%>
		<p> Candidato sem foto<p>
	<%end%>
		<p><strong>Nome: </strong><%= link_to applicant.full_name, applicant,
															 		id: "names-#{applicant.id}" %>
    <p><strong>Formação: </strong><%= applicant.academic %> </p>
		<p><strong>Data de Nascimento: </strong>
					 <%= I18n.l(applicant.birthdate)%></p>
		<br>
	<%end%>
<%end%>

app/views/applicants/new.html.erb
<h1>Cadastar Perfil</h1>

<%= render 'form' %>

app/views/applicants/show.html.erb
<h1>Dados do Candidato</h1>

<dl>
  <dt>Foto</dt>
	<% if @applicant.photo.present?%>
  	<dd id = 'photo'><%= image_tag @applicant.photo, size:'210x150',
																										 alt: 'Foto'%></dd>
	<%else%>
		<p>Candidato sem foto<p>
	<%end%>
	<dt>Nome: </dt>
  <dd><%= @applicant.full_name%>
	<% if head_signed_in? %>
  	<% if @favorite.any? %>
			<%='⭐'%></dd>
    	<p><%= link_to 'Desfavoritar candidato',
									 applicant_favorite_path(@applicant),
									 method: :delete %></p>
  	<% else %>
    	<p><%= link_to 'Favoritar candidato', 
								 applicant_favorites_path(@applicant),
								 method: :post %><p>
  	<% end %>
	<% end %>
  <dt>Nome Social: </dt>
  <dd><%= @applicant.social_name%></dd>
  <dt>Data de nascimento</dt>
  <dd><%= I18n.l(@applicant.birthdate)%></dd>
  <dt>Formação: </dt>
  <dd><%= @applicant.academic%></dd>
  <dt>Descrição: </dt>
  <dd><%= @applicant.description%></dd>
  <dt>Experiência</dt>
  <dd><%= @applicant.experience%></dd>
</dl>
<% if head_signed_in? %>
	<%= link_to 'Deixar Comentário', new_applicant_post_path(@applicant) %><br>
<% end %>

<% if @posts.any? %>
	<% @posts.each do |post| %>
		<p><%= post.head.email %></p>
		<p><%= post.content %></p>
		<p><%= l post.created_at, format: :short %></p>
		<% if head_signed_in? %>
			<%= link_to 'Editar', edit_applicant_post_path(@applicant, post), 
				id: "edit-post#{post.id}"%></p>
			<p><%= link_to 'Deletar', 
				[@applicant, post], 
				method: :delete, 
				id: "delete-post#{post.id}"%></p>
	  <% end %>
	<% end %>
<% end %>
<% if user_signed_in? %>
	<%= link_to "Editar", edit_applicant_path(@applicant) %>
<% end %>