config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  authenticated :user do
    root 'applicants#show', as: :user_authenticated_root
  end
  devise_for :heads, controllers: {
    sessions: 'heads/sessions',
    registrations: 'heads/registrations'
  }
  authenticated :head do
    root 'head_profiles#index', as: :head_authenticated_root
  end
  root 'home#index'
  resources :applicants, only: %i[index show new create edit update] do
    resources :favorites, only: %i[create destroy]
    resources :posts, only: %i[show new create edit update destroy]
  end
  resources :feedbacks, only: [:index]
  resources :head_profiles, only: [:index]
  resources :job_offers, only: %i[index]
  resources :reply_offers, only: %i[index new create]
  resources :job_openings, only: [:index]
  resources :job_vacancies, only: %i[index show new create] do
    get 'search', on: :collection
    resources :feedbacks, only: %i[show new create]
    resources :job_offers, only: %i[new create]
    resources :job_openings, only: %i[show new create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Headhunter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <nav class="navbar navbar-dark bg-dark", style='background-color: #e3f2fd;'>
     <span class="navbar-text">
    <% if user_signed_in? %>
      <%= link_to 'Ver vagas de emprego', job_vacancies_path%>
      <%= link_to 'Home candidato', root_path %>
      <%= link_to 'Meus Feedbacks', feedbacks_path %>
      <%= link_to 'Minhas Propostas', job_offers_path %>
      <%= link_to 'Minhas Vagas', job_openings_path %>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
    </span>
  <%end%>
  <% if head_signed_in? %>
    <%= link_to 'Home headhunter', head_profiles_path%>
    <%= link_to 'Ver perfis cadastrados', applicants_path%>
    <%= link_to 'Ver Propostas respondidas', reply_offers_path%>
    <%= link_to 'Cadastrar vaga de emprego', new_job_vacancy_path %>
    <%= link_to 'Sair', destroy_head_session_path, method: :delete %>
  <%end%>
  <% if !(user_signed_in? || head_signed_in?) %>
    <%= link_to "Candidato", new_user_session_path%>
    <%= link_to "Headhunter", new_head_session_path%>
  <%end%>
  </nav>
  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>